# Generated by Django 4.0.3 on 2022-04-13 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_description_alter_contact_title_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.CharField(choices=[('French', 'French'), ('Italian', 'Italian'), ('Bulgarian', 'Bulgarian'), ('Chinese', 'Chinese'), ('Greek', 'Greek'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Spanish', 'Spanish'), ('Moroccan', 'Moroccan'), ('Lebanese', 'Lebanese'), ('Mediterranean', 'Mediterranean'), ('Turkish', 'Turkish'), ('Thai', 'Thai')], max_length=13),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dificulty',
            field=models.CharField(choices=[('Novice', 'Novice'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], max_length=8),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Starter', 'Starter'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert')], max_length=9),
        ),
    ]
