# Generated by Django 4.0.3 on 2022-04-15 19:58

import cloudinary.models
import cooking_world.common.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_title_alter_contact_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[cooking_world.common.validators.MaxFileSizeInMbValidator(5)], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[cooking_world.common.validators.MaxFileSizeInMbValidator(5)], verbose_name='image'),
        ),
    ]
